# Generated by Django 4.1.4 on 2022-12-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_productmodel_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(default='https://static.freeimages.com/images/home/filetypes/photo.png'),
        ),
    ]
